[pytest]
pythonpath = experiment_automation
testpaths =
    experiment_automation/tests/API
    experiment_automation/tests/UI

addopts = -v -s --alluredir=allure-results

python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: Basic tests
    regression: Full regression